---
kind: pipeline
name: grafana-javascript-agent

steps:
- name: Install dependencies
  image: node:lts-stretch
  commands:
  - yarn install --frozen-lockfile

- name: Build
  image: node:lts-stretch
  commands:
  - yarn build

- name: Lint
  image: node:lts-stretch
  commands:
  - yarn quality
---
kind: signature
hmac: 482b76729e2519c49e513979848463742d31f4cd0342fe8fec35682a1fd43bba

...
