---
kind: pipeline
name: grafana-javascript-agent

steps:
- name: Install dependencies
  image: node:lts-stretch
  commands:
  - yarn install --frozen-lockfile

- name: Build
  image: node:lts-stretch
  commands:
  - yarn build

- name: Lint
  image: node:lts-stretch
  commands:
  - yarn quality

- name: Publish
  image: node:lts-stretch
  commands:
  - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
  - yarn run publish --yes from-git
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event:
    - tag
---
kind: signature
hmac: df2eea003691cf889c81ee1584eea81c256a2821fa024fa92e2d0f09c82daa1b

...
