---
kind: pipeline
name: grafana-javascript-agent

steps:
- name: Install dependencies
  image: node:lts-stretch
  commands:
  - yarn install --frozen-lockfile

- name: Build
  image: node:lts-stretch
  commands:
  - yarn build

- name: Lint
  image: node:lts-stretch
  commands:
  - yarn quality

- name: Publish
  image: node:lts-stretch
  commands:
  - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
  - yarn run publish from-git
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    branch:
    - main
---
kind: signature
hmac: 42c3ae051e96886dbba72b31ab8d568254a9cddfd35718664a21803a6ee52186

...
