---
kind: pipeline
name: grafana-javascript-agent

steps:
- name: Install dependencies
  image: node:lts-stretch
  commands:
  - yarn install --frozen-lockfile

- name: Build
  image: node:lts-stretch
  commands:
  - yarn build

- name: Lint
  image: node:lts-stretch
  commands:
  - yarn quality

- name: Publish
  image: node:lts-stretch
  commands:
  - git fetch --tags
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - yarn run publish from-git --yes --no-verify-access
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event:
    - tag
---
kind: signature
hmac: 7446b40b5c9c110e103c2f9fbeba5d8058461e22d47143f49374b9ee62a35c51

...
